### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by fridzema** [Brotzka/laravel-dotenv-editor#1]
Dear Brotzka,
I really want to use your great package in our application!
But after install and whatever key i am trying to get (APP_DEBUG, APP_ENV etc.) i get the error:
DotenvEditor.php line 258:
Undefined offset: 1

I am using php7, if that is relevant for you...

I hope that you or anybody else can help me out.

**Comment by Corvisier** [comment]
I had the same issue with PHP7.
Just change line 258 to:

$returnArray[$entry[0]] = isset($entry[1]) ? $entry[1] : null;

**Comment by Brotzka** [comment]
Hey guys, 
I will take a look at it later and will fix/merge it. Thanks for the hint and thank you @Corvisier

**Comment by fridzema** [comment]
@Corvisier Thanks it works for now!
@Brotzka The only thing i did was this:
`      $env = new DotenvEditor();

      $env->getValue('APP_KEY');`

**Comment by Brotzka** [comment]
Merged the pull request from Corvisier

**Comment by AryHouessou** [comment]
Hi Dear.
I'm new laravel coder and I want to use your package to set dynamically my .env
But after installation, how can I go to interface in my browser ?
