### ISSUE TITLE
.env file not loading

### ISSUE THREAD

**Issue by PatrickHeppler** [Brotzka/laravel-dotenv-editor#10]
I just installed dotenv-editor on my dev box. But I can't load .env file in overview. No error in laravel.log, the key value flelds just keep empty. Paths seem correct because I can backup and download the .env. I'm on Laravel 5.2

**Comment by Brotzka** [comment]
Hey,

I am doing my best to find a solution. But that's the first time this problem occurs.

**Comment by PatrickHeppler** [comment]
It's weird, overview doesn't show anything, but I can run:
```
<?php

use Brotzka\DotenvEditor\DotenvEditor;

$env = new DotenvEditor();
dd($env->getContent());
```

**Comment by Brotzka** [comment]
Do you get some JavaScript errors? Maybe the problem is VueJS.

**Comment by PatrickHeppler** [comment]
Thx for the hint. I get a 404 on a XHR to getdetails. Issue is my routing, my backend routes use a prefix.

**Comment by Brotzka** [comment]
Ok. I've a pull-request that will fix this. I'm going to review and merge this pull-request the next days. Than your problem should be solved.

**Comment by PatrickHeppler** [comment]
Works now with the 2.0.3 release. Thx!

**Comment by Brotzka** [comment]
Great! 👍
