### ISSUE TITLE
php artisan route:list broken

### ISSUE THREAD

**Issue by affektde** [Brotzka/laravel-dotenv-editor#13]
```
Route::get(config('dotenveditor.route') . '/test', '\App\Http\Controllers\EnvController@test');
```

This line is breaking _php artisan route:list_, if you have set your application's namespace to another name like "App".

_vendor/brotzka/laravel-dotenv-editor/src/Http_ => line 27

**Comment by Mahmoudz** [comment]
Same problem when I run `php artisan route:list` I get the following error:

```shell
[ReflectionException]
Class App\Http\Controllers\EnvController does not exist
```

**Comment by PatrickHeppler** [comment]
@Brotzka see my PR
