### ISSUE TITLE
[L5.3]: The array is outputting 1 empty row always.

### ISSUE THREAD

**Issue by Tjoosten** [Brotzka/laravel-dotenv-editor#14]
<img width="594" alt="schermafbeelding 2016-11-03 om 06 41 51" src="https://cloud.githubusercontent.com/assets/5157609/19956840/b3d3c8e0-a190-11e6-9a41-c6affb1586fd.png">

**Comment by Tjoosten** [comment]
It only appears when the.env file have a empty new line. @Brotzka maybe you can filter this line out. Because i see it as user unfriendly experience when there is a empty table row.

**Comment by Brotzka** [comment]
Hey @Tjoosten! I will include this within the next release. Thanks :)

**Comment by PatrickHeppler** [comment]
This seems the issue for #18

**Comment by Brotzka** [comment]
Should be fixed by pull-request #19
