### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by de-raaf-media** [Brotzka/laravel-dotenv-editor#28]
Nice work! One problem. I get a permission denied error. I use Capistrano to copy the env file to the production server.

**Comment by de-raaf-media** [comment]
For now I change the owner and group to nginx user www-data. But I don't know how secure this is:

chown -R www-data:www-data .env.

**Comment by rambo666** [comment]
Is it safe ?

**Comment by de-raaf-media** [comment]
I think it is relatively secure because the .env file is not in the public dir.
