### ISSUE TITLE
Error in Router::group after upgrade (v2.0.14 => v2.1.0)

### ISSUE THREAD

**Issue by seedgabo** [Brotzka/laravel-dotenv-editor#61]
after upgrade the package something broken on the routes of the package:

```
In Router.php line 366:

  Argument 1 passed to Illuminate\Routing\Router::group() must be of the type
   array, string given, called in ....../vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 223
```

**Comment by Brotzka** [comment]
Could you be more specific? Which file causes the error?

**Comment by nguyentranchung** [comment]
@seedgabo 
your route being caching.
run
```bash
php artisan route:clear
```
or
```
php artisan route:cache
```
to fix this.

**Comment by seedgabo** [comment]
![image](https://user-images.githubusercontent.com/11755309/49890921-44fc0180-fe13-11e8-9549-9f180e9f00cd.png) im not sure if this help.

route:clear doesnt work because app seems to be broken in the Route Provider

**Comment by nguyentranchung** [comment]
@seedgabo 
one more step to clear your config

Dev environment
```
php  artisan config:clear
php artisan route:clear
```

Production environment
```
php  artisan config:cache
php artisan route:cache
```

**Comment by nguyentranchung** [comment]
I just know that your config file is old. Please replace the new config file with the following command:
```
php artisan vendor:publish --provider=Brotzka\DotenvEditor\DotenvEditorSer
viceProvider --tag=config --force
```

**Comment by huuloc4193** [comment]
The same.
Can not replace any new config file as your guide.
I saw a message error:"Argument 1 passed to Illuminate\Routing\Router::group() must be of the type
   array, string given, called in /path/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on lin
  e 223"
Can not do anything.

**Comment by huuloc4193** [comment]
I just fixed it.
Go to /path/vendor/brotzka/laravel-dotenv-editor/routes/web.php and open it.
Replace the code with following code:
`<?php
/**
 * Created by PhpStorm.
 * User: Fabian
 * Date: 19.07.16
 * Time: 06:04
 */
if (config('dotenveditor.activated')) {
    Route::group([
        'middleware' => config('dotenveditor.middleware'),
        'middlewareGroups' => config('dotenveditor.middlewareGroups')
    ],
        function () {
            Route::get('/', 'EnvController@overview')->name('index');
            Route::post('/add', 'EnvController@add')->name('add');
            Route::post('/update', 'EnvController@update')->name('update');
            Route::get('/createbackup', 'EnvController@createBackup')->name('createbackup');
            Route::get('/deletebackup/{timestamp}', 'EnvController@deleteBackup')->name('deletebackup');
            Route::get('/restore/{backuptimestamp}', 'EnvController@restore')->name('restore');
            Route::post('/delete', 'EnvController@delete')->name('delete');
            Route::get('/download/{filename?}', 'EnvController@download')->name('download');
            Route::post('/upload', 'EnvController@upload')->name('upload');
            Route::get('/getdetails/{timestamp?}', 'EnvController@getDetails')->name('getdetails');
        }
    );
}`

**Comment by ericamigo** [comment]
@huuloc4193 you shud not replace the core code.

the solution is actually in `/config/dotenveditor.php`

replace the value of `'route' => '/enveditor',` to
```
'route' =>  [
    'prefix' => 'enveditor'
],
```

**Comment by huuloc4193** [comment]
@ericamigo Ok bro! I think there were 2 errors that need to fix.

**Comment by seedgabo** [comment]
delete the config/dotenveditor.php should work

**Comment by nguyentranchung** [comment]
@seedgabo 
just keep issue open, many people have encountered this error when upgrading and need to know how to fix it.

![image](https://user-images.githubusercontent.com/9611224/50036545-ea4dea00-004c-11e9-83f3-dd6d9e3a7ff8.png)

Look at this picture, and we'll know why there is such a error.

**Comment by joukhar** [comment]
same problem but i fixed it !
run composer update and then run php artisan route:clear and then
use attributes before using route group function exemple:

Route::name('admin.')->group(function () {
    Route::get('/dashboard', function () {
        // Route assigned name 'admin.dashboard'...
    })->name('dashboard');
});
