### ISSUE TITLE
Cannot use Illuminate\Support\Str as Str because the name is already in use 

### ISSUE THREAD

**Issue by almamund** [Brotzka/laravel-dotenv-editor#73]
Hello, 
There is an error in DotEnvEditor.php. You have used this twice
`use Illuminate\Support\Str;`

![Error](https://user-images.githubusercontent.com/5769361/116784982-fa997f00-aab8-11eb-98a3-aa59d62c0de6.JPG)

**Comment by delia-curiel** [comment]
yes, please, I have the same issue 
@Brotzka

**Comment by riteshinfyom** [comment]
pls merge this asap, I have same issue

**Comment by Rikj000** [comment]
@Brotzka please merge this PR, currently your package is in a broken state due to it
